### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting..

### ISSUE THREAD

**Issue by ningji** [dulajkavinda/performance#1]
At this step: setting up [socket.io](http://socket.io/) node server

1. ningji@ningji-ThinkCentre-M920q:~/2keep/performance/server$ ag "mongoose.connect"
socket_main.js
mongoose.connect("mongodb://127.0.0.1/perfData", { useNewUrlParser: true });

2. when i do "npm start", it keeps on giving this error:

MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (/home/ningji/2keep/performance/server/node_modules/mongoose/lib/connection.js:796:32)
    at /home/ningji/2keep/performance/server/node_modules/mongoose/lib/index.js:328:10
    at /home/ningji/2keep/performance/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/ningji/2keep/performance/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/home/ningji/2keep/performance/server/node_modules/mongoose/lib/index.js:1149:10)
    at Mongoose.connect (/home/ningji/2keep/performance/server/node_modules/mongoose/lib/index.js:327:20)
    at Object.<anonymous> (/home/ningji/2keep/performance/server/socket_main.js:2:10)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      '127.0.0.1:27017' => ServerDescription {
        _hostAddress: HostAddress { isIPv6: false, host: '127.0.0.1', port: 27017 },
        address: '127.0.0.1:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 114953270,
        lastWriteDate: 0,
        error: MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017
            at connectionFailureError (/home/ningji/2keep/performance/server/node_modules/mongodb/lib/cmap/connect.js:293:20)
            at Socket.<anonymous> (/home/ningji/2keep/performance/server/node_modules/mongodb/lib/cmap/connect.js:267:22)
            at Object.onceWrapper (node:events:642:26)
            at Socket.emit (node:events:527:28)
            at emitErrorNT (node:internal/streams/destroy:157:8)
            at emitErrorCloseNT (node:internal/streams/destroy:122:3)
            at processTicksAndRejections (node:internal/process/task_queues:83:21)
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  }
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by ningji** [comment]
First of all, this is a great app !

A little bit more info:
1. ubuntu 20.04
2. i don't have yarn, so used npm to install
3. install redis, i followed: https://phoenixnap.com/kb/install-redis-on-ubuntu-20-04
    sudo systemctl restart redis.service
    
    i do see the UI loads up with cpu/memory status changing, until socket.io node server crashes...
